name: Run tests on push

on: [ push ]

jobs:
  testing:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - with:
          node-version: 16
      - run: npm test
      - run: npm run generate-badge
